### ISSUE TITLE
Feature: automatically use deposits in low-risk DeFi products

### ISSUE THREAD

**Issue by vicsn** [721labs/partial-common-ownership#44] opened 2022-01-22 16:18 UTC
This could lower the opportunity cost of using the contracts

**Comment by will-holley** [comment] 2022-01-25 16:21
This issue is a duplicate of https://github.com/721labs/partial-common-ownership/issues/29.  Let's continue the discussion there.

**Closed by will-holley** 2022-01-25 16:21 UTC
